import { geistMono, geistSans, incognito, pixelifySans } from "@/assets/fonts";
import MotionConfigWrapper from "@/components/motion-config";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Microlab Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "mx-auto font-sans antialiased",
          geistSans.variable,
          geistMono.variable,
          incognito.variable,
          pixelifySans.variable
        )}
      >
        <Providers>
          <MotionConfigWrapper>{children}</MotionConfigWrapper>
        </Providers>
      </body>
    </html>
  );
}
